# Generated by Django 3.0.4 on 2021-05-21 16:36

import backend.base.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=backend.base.services.upload_file),
        ),
    ]
