# Generated by Django 3.0.4 on 2021-05-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_auto_20210521_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='avatar',
        ),
    ]
